services:

  mysql:
    image: mysql:8.4
    container_name: ecommerce_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bf6nvbshj
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pbf6nvbshj"]
      interval: 5s
      timeout: 5s
      retries: 10

  fastapi:
    build: ./fastapi_backend
    container_name: ecommerce_fastapi
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi_backend/.env
    depends_on:
      mysql:
        condition: service_healthy

  django:
    build: ./django_admin
    container_name: ecommerce_django
    ports:
      - "8001:8001"
    env_file:
      - ./fastapi_backend/.env
    depends_on:
      fastapi:
        condition: service_started

  frontend:
    build: ./frontend
    container_name: ecommerce_frontend
    ports:
      - "5173:5173"
    depends_on:
      fastapi:
        condition: service_started

volumes:
  mysql_data: